trigger:
- '*'

pool:
  name: Hosted VS2017

steps:
- task: YarnInstaller@3
  displayName: 'Use Yarn 1.x'
  inputs:
    checkLatest: true

- task: Yarn@3
  displayName: 'Yarn install'
  inputs:
    Arguments: install

- task: Yarn@3
  displayName: 'Yarn run build'
  inputs:
    Arguments: 'run build'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: './build'