export const CLIENT = {
    LOADED: "CLIENT_LOADED"
};

export const DEVICES = {
    LOADED: "DEVICES_LOADED",
    UPDATED:"DEVICE_UPDATED",
    CREATED:"DEVICE_CREATED",
};

export const DEVICE_TYPES = {
    LOADED: "DEVICE_TYPES_LOADED"
};

export const MEASUREMENT_TYPES = {
    LOADED: "MEASUREMENT_TYPES_LOADED"
};

export const DEVICE_GROUPS = {
    LOADED: "DEVICE_GROUPS_LOADED",
    UPDATED:"DEVICE_GROUP_UPDATED",
    CREATED:"DEVICE_GROUP_CREATED",
};

export const USERS = {
    LOADED: "USERS_LOADED",
    UPDATED:"USER_UPDATED",
    CREATED:"USER_CREATED",
};

export const RULES = {
    LOADED: "RULES_LOADED",
    UPDATED:"RULE_UPDATED",
    CREATED:"RULE_CREATED",
};

export const STATUS = {
    FETCHING: "STATUS_FETCHING",
    SUCCESS: "STATUS_SUCCESS",
    ERROR: "STATUS_ERROR",
    RESET: "STATUS_RESET"
}